language: objective-c
osx_image: xcode8
env:
- DESTINATION="OS=10.0,name=iPhone 7" SCHEME="XLSwiftKit" SDK=iphonesimulator10.0

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project XLSwiftKit.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project XLSwiftKit.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
