osx_image: xcode8
language: objective-c

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./swiftlint.sh; fi
script:
  - xcodebuild clean build -project Compass.xcodeproj -scheme Compass-iOS -sdk iphonesimulator
  - xcodebuild test -project Compass.xcodeproj -scheme "Compass-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
  - xcodebuild clean build -project Compass.xcodeproj -scheme Compass-Mac -sdk macosx
  - xcodebuild test -project Compass.xcodeproj -scheme Compass-Mac -sdk macosx
notifications:
  email: false
after_success:
- bash <(curl -s https://codecov.io/bash)
